apiVersion: v1
kind: Namespace
metadata:
  name: adplat
  labels:
    name: adplat
---
apiVersion: v1
kind: Service
metadata:
  name: adplat-httpd-svc
  namespace: adplat
spec:
  type: NodePort
  ports:
    - name: http-port
      nodePort: 30080
      port: 80
      targetPort: 80
  selector:
    app: adplat-httpd-dm
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adplat-httpd
  namespace: adplat
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    #由于replicas为2,则整个升级,pod个数在1-3个之间
    rollingUpdate:
      ##滚动升级时会先启动1个pod
      maxSurge: 1
      ##滚动升级时允许的最大Unavailable的pod个数
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: adplat-httpd-dm
    spec:
      ##k8s将会给应用发送SIGTERM信号，可以用来正确、优雅地关闭应用,默认为30秒
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      containers:
        - name: adplat-httpd
          image: httpd:alpine
          imagePullPolicy: Always
