apiVersion: v1
kind: List
items:
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: adplat-ingress
      namespace: adplat
      annotations:
        kubernetes.io/ingress.class: "nginx"
        # 实现pod层面的负载均衡，只需要配置replicas即可
        nginx.ingress.kubernetes.io/upstream-hash-by: "$request_uri"
    spec:
      rules:
        - host: ingress.adplat.com
          http:
            paths:
              - path: /
                backend:
                  serviceName: adplat-httpd-svc
                  servicePort: 80